### ISSUE TITLE
test_p2p is failing since 3128b4e

### ISSUE THREAD

**Issue by bijancn** [gsec/eZchat#20] opened 2014-10-10 13:35 UTC
Maybe don't only fix it but actually use it. Or add an integration test where the cli is started. It shouldn't have been possible for me to break the pipe without any test failing.

**Comment by bijancn** [comment] 2014-10-10 13:40
Linking isnt done in the title it seems: 3128b4e5362bff0f061ee3405efc2ff60cdf3b88

**Comment by JNicL** [comment] 2014-10-10 14:35
- It has been in use for a while.
- I don't know if u two r up2date: ez_cli.py is fully working and rdy 4 use.

Try:

-start server:
python ez_server "" 1234

-start two client sessions:
python ez_cli.py bijan -s startup.txt
python ez_cli.py gui -s startup.txt

_In bijan_
-connect each other (will be automated soon):
:ips server

-request public key:
:key gui

-send him a msg:
:send gui MustBeConnected
- Concerning tests, I don't know how to write tests for cli environment maybe you can come up wih an idea. I googled, but have not found anything useful.
- I will fix the test_p2p now

**Comment by bijancn** [comment] 2014-10-10 14:41
You should close the issue with the commit that fixes it. Not just say u do it. It helps to keep track of things.

Next thing, concerning 'up2date' : git pull -> Already up-to-date.
python ez_server.py "" 1234 -> 
Traceback (most recent call last):
  File "ez_server.py", line 2, in <module>
    from ez_p2p import client, p2pCommand
  File "/home/bijancn/eZchat/ez_p2p.py", line 17, in <module>
  File "/home/bijancn/eZchat/ez_user_methods.py", line 13, in <module>
  File "/home/bijancn/eZchat/ez_process/ez_process_base.py", line 83, in **init**
    assert not attr in cls.handlers
AssertionError

??? Have you pushed everything?

**Comment by JNicL** [comment] 2014-10-10 14:47
Ya, I had pushed everything, the reason it was working for me is because of the old .pyc files.
-> pushed and tested.
- Tell me if something s not working.

**Comment by JNicL** [comment] 2014-10-10 15:05
- I see the problem with the docs. I made cl.cl purely global which solved that errer, however, another bug shows up

Running Sphinx v1.2.2
loading pickled environment... not yet created
building [latex]: all documents
updating environment: 16 added, 0 changed, 0 removed
reading sources... [  6%] ez_cli  
Exception occurred:
  File "/home/nick/eZchat/ez_user.py", line 43, in **init**
    self.UID = SHA.new(self.name + self.public_key).hexdigest()
TypeError: cannot concatenate 'str' and 'NoneType' objects
- This has to do with the problem I have discussed in another issue.
- Shall I push this?

**Comment by bijancn** [comment] 2014-10-10 15:56
Nice. Now I see messages flying arround with proper HMAC and tests seem to work. With which issue has the sphinx documentation problem to do? What can you push?

**Comment by JNicL** [comment] 2014-10-10 16:07
I can push a version where sphinx compiles, however, I had to disable 
- init_client() 

in ez_cli and remove
- self.myself = eu.User(name=self.name)
- self.UserDatabase.add_entry(self.myself)

in ez_api which is certainly not what we want.

**Comment by bijancn** [comment] 2014-10-10 16:52
No we need a proper fix. Not worth to push that.

**Comment by JNicL** [comment] 2014-10-10 16:54
I will push a working version where ez_cli.rst is disabled.

**Comment by bijancn** [comment] 2014-10-17 12:12
Can we close this now? I lost track..

**Comment by JNicL** [comment] 2014-10-17 12:28
We can close this issue, however, the main problem is still present. Ez_cli doc won't compile which is due to `.. automodule:: ez_cli` in ez_cli.rst. Sphinx tries to run the code which is done wrong. The problem is solved by implementing the modules separately or by writing the doc from scratch which should be done anyway in the case of ez_cli.

**Closed as completed by JNicL** 2014-10-17 12:28 UTC
